# Ansible Inventory — Auto-generated by Terraform
# Do not edit manually — regenerated on every terraform apply

[controller]
controller ansible_host=192.168.122.55 ansible_user=root

[edge_nodes]
edge-node-1 ansible_host=${vm1_ip} ansible_user=ubuntu zone=zone1 vm_id=${vm1_id} private_ip=${vm1_private_ip}
edge-node-2 ansible_host=${vm2_ip} ansible_user=ubuntu zone=zone2 vm_id=${vm2_id} private_ip=${vm2_private_ip}

[standby]
edge-node-3 ansible_host=${vm3_ip} ansible_user=ubuntu zone=standby vm_id=${vm3_id} private_ip=${vm3_private_ip}

[all_vms:children]
edge_nodes
standby

[all:vars]
ansible_ssh_private_key_file = ~/.ssh/edge-key.pem
ansible_python_interpreter   = /usr/bin/python3
ansible_ssh_common_args      = '-o ProxyCommand="ssh -W %h:%p -q root@192.168.122.55 -o StrictHostKeyChecking=no" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
mqtt_broker                  = 192.168.122.1
mqtt_port                    = 1883
proxy_http                   = http://10.0.10.11:3128
