#!/bin/bash
# =============================================================
# generate-inventory.sh
# Reads prometheus/targets.json and generates
# ansible/inventory.ini for use by all Ansible playbooks.
# Run after update-targets.sh or after terraform apply.
# =============================================================

set -euo pipefail

# -------------------------------------------------------------
# Configuration
# -------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGETS_FILE="${SCRIPT_DIR}/../prometheus/targets.json"
INVENTORY_FILE="${SCRIPT_DIR}/../ansible/inventory.ini"
CONTROLLER_IP="192.168.122.55"
CONTROLLER_USER="root"
VM_USER="ubuntu"
KEY_FILE="~/.ssh/edge-key.pem"
PROXY_COMMAND="ssh -W %h:%p -q root@${CONTROLLER_IP} -o StrictHostKeyChecking=no"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Generating Ansible inventory from targets.json..."

# Check targets file exists and is valid
if [[ ! -f "$TARGETS_FILE" ]]; then
    echo "ERROR: targets.json not found at $TARGETS_FILE"
    echo "Run update-targets.sh first."
    exit 1
fi

if ! jq . "$TARGETS_FILE" > /dev/null 2>&1; then
    echo "ERROR: targets.json is not valid JSON."
    exit 1
fi

VM_COUNT=$(jq '. | length' "$TARGETS_FILE")
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Found ${VM_COUNT} VM(s) in targets.json"

# -------------------------------------------------------------
# Build inventory file
# -------------------------------------------------------------
cat > "$INVENTORY_FILE" << HEADER
# =============================================================
# Ansible Inventory — Auto-generated by generate-inventory.sh
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# Do not edit manually — regenerated by generate-inventory.sh
# =============================================================

[controller]
controller ansible_host=${CONTROLLER_IP} ansible_user=${CONTROLLER_USER}

HEADER

# Separate VMs by zone
echo "[edge_nodes]" >> "$INVENTORY_FILE"
jq -r '.[] | select(.labels.zone != "standby") |
    .labels.vm_name + " " +
    "ansible_host=" + (.targets[0] | split(":")[0]) + " " +
    "zone=" + .labels.zone + " " +
    "vm_id=" + .labels.vm_id + " " +
    "openrc=" + .labels.openrc
' "$TARGETS_FILE" >> "$INVENTORY_FILE" 2>/dev/null || true

echo "" >> "$INVENTORY_FILE"
echo "[standby]" >> "$INVENTORY_FILE"

# Get VM3 floating IP directly from OpenStack (since it's shutoff, not in targets.json)
VM3_FIP=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    root@192.168.122.55 \
    "source /root/bin/edge-monitoring-openrc.sh && \
     openstack floating ip list -f json | \
     jq -r '.[] | select(.Port == null) | .\"Floating IP Address\"'" 2>/dev/null)

VM3_ID=$(ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    root@192.168.122.55 \
    "source /root/bin/edge-monitoring-openrc.sh && \
     openstack server show edge-node-3 -f value -c id" 2>/dev/null)

if [ -n "$VM3_FIP" ]; then
    echo "edge-node-3 ansible_host=${VM3_FIP} zone=standby vm_id=${VM3_ID} openrc=edge-monitoring-openrc.sh" >> "$INVENTORY_FILE"
fi

# Group children and global vars
cat >> "$INVENTORY_FILE" << FOOTER

[all_vms:children]
edge_nodes
standby

[all:vars]
ansible_user=${VM_USER}
ansible_ssh_private_key_file=${KEY_FILE}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o ProxyJump=root@${CONTROLLER_IP} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
mqtt_broker=192.168.122.1
mqtt_port=1883
proxy_http=http://10.0.10.11:3128
FOOTER

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Inventory written to: ${INVENTORY_FILE}"
echo ""
echo "Preview:"
echo "----------------------------------------"
cat "$INVENTORY_FILE"
echo "----------------------------------------"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Done."
